# Setup
title: Dr. P1ng
description: CTF Player, Hacker e Investigador de Ciberseguridad
url: https://drp1ng.github.io
avatar: /avatar.jpeg
paginate: 8
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: P1ngDr
  card: summary
logo: logo.png
social:
  name: Dr. P1ng
  links:
    - https://twitter.com/P1ngDr
    - https://github.com/DrP1ng
google_site_verification: xxxxx
lang: es

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: G-9JKFQV6M4P

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Dr. P1ng
  url: https://github.com/DrP1ng/
#  email: vszhub@gmail.com
